flags: {}
packages:
- '.'
- location:
    git: git@github.com:krisajenkins/sigym4-geometry.git
    commit: 787977fc3f2065ebda57d0e3feed22a96668956d
- location:
    git: https://github.com/meteogrid/spatial-reference.git
    commit: de83fe1319e14937c71e82baeca3f5f3411d1a49
extra-deps: []
resolver: lts-5.0
